extends Node
## Sound effects (autoload "Sfx"). Call Sfx.play("hit") from anywhere.
## The .wav files are generated by tools/make_sounds.py.

const NAMES := ["click", "buy", "equip", "error", "swing", "uppercut", "hit", "hit_big",
		"block", "jump", "land", "step", "ko", "round", "fight", "victory", "defeat"]
const VOICES := 10

var streams := {}
var players: Array = []
var next := 0


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	for n in NAMES:
		var path := "res://sfx/%s.wav" % n
		if ResourceLoader.exists(path):
			streams[n] = load(path)
	for k in VOICES:
		var p := AudioStreamPlayer.new()
		add_child(p)
		players.append(p)


## pitch_jitter: random pitch variation (0.1 = +/-10%) so repeated sounds don't get boring.
func play(sound: String, pitch_jitter: float = 0.0, volume_db: float = 0.0) -> void:
	if not GameData.settings.get("sound", true):
		return
	if not streams.has(sound):
		return
	var p: AudioStreamPlayer = players[next]
	next = (next + 1) % VOICES
	p.stream = streams[sound]
	p.pitch_scale = 1.0 + randf_range(-pitch_jitter, pitch_jitter)
	p.volume_db = volume_db
	p.play()
